### ISSUE TITLE
Migrate to agritheory/test_utils

### ISSUE THREAD

**Issue by MyuddinKhatri** [agritheory/electronic_payments#31]
- [x] Common pre-commit (done via #41)
- [x] Poetry-based toml (done via #41)
- [x] pytest-coverage (done via #41)
- [x] update customizations (done via #41)
- [x] backport (done via #41)
- [x] track overrides (done via #41)
- [ ] postgres tests
- [ ] dokos tests
- [ ] import common test fixtures
- [ ] translate documentation
